### ISSUE TITLE
Can't run on iOS

### ISSUE THREAD

**Issue by paprikka** [contentment/AndroidInAppBilling#1]
Getting this error when running the app via `$ cordova run ios`

/Users/rafal/Developer/lab/padify-toolkit-tests/Maciek/Geist/platforms/ios/Geist Magazine/Plugins/com.smartmobilesoftware.androidinappbilling/SkuDetails.h:12:9: fatal error:
      'ConvertibleToDictioanry.h' file not found
#import "ConvertibleToDictioanry.h"
        ^

** BUILD FAILED **

**Comment by Czajnikowski** [comment]
63386ad0faf0e73ba4f6971cc4bf08f32f4f0067

**Comment by paprikka** [comment]
Did you test it with $ cordova run ios?

On 26 May 2015 at 11:56, Czajnikowski <notifications@github.com> wrote:

> Closed #1 <https://github.com/contentment/AndroidInAppBilling/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/contentment/AndroidInAppBilling/issues/1#event-313653028>
> .
>



-- 
Rafał Pastuszak

Developer · Designer · Sometimes speaks Persian in sleep.
http://flavours.me/rpastuszak
@rafalpast

**Comment by Czajnikowski** [comment]
Give me 10 minutes, I have seen the error, but I thought it’s related to my local changes.

**Comment by Czajnikowski** [comment]
Give me 10 minutes, I have seen the error, but I thought it’s related to my local changes.

**Comment by Czajnikowski** [comment]
0a9905143dec0f27f0d10db6d8fbdedf45d37014
